// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQ2DIQGHVvQHfRUQ0MZ8DGJEslF3axmM',
    appId: '1:201645168726:web:52f1213e68abccda9d03f7',
    messagingSenderId: '201645168726',
    projectId: 'safeband-a3b89',
    authDomain: 'safeband-a3b89.firebaseapp.com',
    storageBucket: 'safeband-a3b89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulmg9z_Bz_8sfevHW3ofLVyDGPoMNRtQ',
    appId: '1:201645168726:android:d57a86880b6e9f1f9d03f7',
    messagingSenderId: '201645168726',
    projectId: 'safeband-a3b89',
    storageBucket: 'safeband-a3b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTSMLksIYanD4PI8qFfe3FcyiOWRzC34',
    appId: '1:201645168726:ios:5d9268088519ba6f9d03f7',
    messagingSenderId: '201645168726',
    projectId: 'safeband-a3b89',
    storageBucket: 'safeband-a3b89.firebasestorage.app',
    iosBundleId: 'com.example.safeband',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjTSMLksIYanD4PI8qFfe3FcyiOWRzC34',
    appId: '1:201645168726:ios:5d9268088519ba6f9d03f7',
    messagingSenderId: '201645168726',
    projectId: 'safeband-a3b89',
    storageBucket: 'safeband-a3b89.firebasestorage.app',
    iosBundleId: 'com.example.safeband',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxQ2DIQGHVvQHfRUQ0MZ8DGJEslF3axmM',
    appId: '1:201645168726:web:10942db785f8ab0e9d03f7',
    messagingSenderId: '201645168726',
    projectId: 'safeband-a3b89',
    authDomain: 'safeband-a3b89.firebaseapp.com',
    storageBucket: 'safeband-a3b89.firebasestorage.app',
  );
}
